### ISSUE TITLE
海康内部有开发macos版的吗？

### ISSUE THREAD

**Issue by jiuyuego** [CoderXiaohui/hk-SADPTools-mac-Chinese#1]
海康内部有开发macos版的吗？

**Comment by CoderXiaohui** [comment]
有的，海康威视英文站有， https://www.hikvision.com/en/support/tools/hitools/clea8b3e4ea7da90a9/

**Comment by CoderXiaohui** [comment]
有的，海康威视国际站有 ，https://www.hikvision.com/en/support/tools/hitools/cl3620e9fb51dfac31/

**Comment by CoderXiaohui** [comment]
我修改了ReadMe ,你可以看下
